### PR TITLE
feat: exposes app via rpc.walletconnect.com

### PR DESCRIPTION
**Pull request by arein**
# Testing

`curl -vvv -X POST -H "Content-Type:application/json" "https://dev.rpc.walletconnect.com/v1/?chainId=eth:1&projectId=someid" -d '{"id":"1660887896683","jsonrpc":"2.0","method":"eth_chainId","params":[]}'`

### CODE REVIEW

**Review by sbc64 — APPROVED** [review]
This looks great :+1: :+1:

**Review by HarryET — CHANGES_REQUESTED** [review]
Are we only having a prod instance of this? not a staging and dev...

**Comment by arein** [comment]
> Are we only having a prod instance of this? not a staging and dev...

Staging and dev are also already set up

`terraform -chdir=terraform workspace select staging && terraform -chdir=terraform apply`

**Comment by arein** [comment]
@HarryET merging as it seems your only concern here was addressed

**Pull request merged**
